
jobs:

  demo1:
    name: Demo1

    context:

      task-defaults:
        traits:
          windows: true

      tasks:
        exit_stati:
          scripts:

            succeed:
              body: |
                exit /b 0

            fail:
              body: |
                exit /b 1
              ignore-state: true



