
jobs:

  tasklist:

    context:

      task-defaults:
        traits:
          windows: true

      tasks:

        tasklist:
          scripts:
            tasklist:
              timeout: 10
              body:  tasklist


  exit_stati:

    context:

      task-defaults:
        traits:
          windows: true

      tasks:

        exit_stati:
          scripts:
            succeed:
              timeout: 10
              body: |
                exit /b 0
            fail:
              timeout: 10
              body: |
                exit /b 1
              ignore-state: true

  list_env_vars:

    context:

      task-defaults:
        traits:
          windows: true

      tasks:
        list_env_vars:
          timeout: 10
          scripts:
            list_env_vars:
              body: set

  sleep_and_timeouts:

    context:

      task-defaults:
        traits:
          windows: true

      tasks:
        timeout:
          scripts:
            violating_timeout:
              body: ping -n 10 127.0.0.1
              timeout: 3
            sleep:
              body: ping -n 30 127.0.0.1
              timeout: 45
